=== dileepcg/KTAB/examples/smp/doc/smp.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="Scenario">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="name" type="xs:string"/>
        <xs:element name="desc" type="xs:string"/>
        <xs:element name="prngSeed" type="xs:string"/>
        <xs:element ref="ModelParameters" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="Dimensions"  minOccurs="0" maxOccurs="1" />
        <xs:element ref="Actors"/>
        <xs:element ref="IdealAdjustment" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="ModelParameters">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="StateTransitions" type="xs:string"/>
        <xs:element name="ResolutionVoting" type="xs:string"/>
        <xs:element name="ResolutionPCE" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="Dimensions">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="dName"  minOccurs="1"  maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="dName">
    <xs:simpleType>
      <xs:restriction base="xs:string">
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  
  <xs:element name="Actors">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Actor" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Actor">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="name" type="xs:string"/>
        <xs:element name="description" type="xs:string"/>
        <xs:element name="capability">
          <xs:simpleType>
            <xs:restriction base="xs:decimal">
              <xs:minInclusive value="0.0"/>
              <xs:maxInclusive value="1000.0"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element ref="Position" />
        <xs:element ref="Salience" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="Position">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="dCoord"  minOccurs="1"  maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="dCoord">
    <xs:simpleType>
      <xs:restriction base="xs:decimal">
        <xs:minInclusive value="0.0"/>
        <xs:maxInclusive value="100.0"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  
  <xs:element name="Salience">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="dSal" minOccurs="1"  maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="dSal">
  
    <xs:simpleType>
      <xs:restriction base="xs:decimal">
        <xs:minInclusive value="0.0"/>
        <xs:maxInclusive value="100.0"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  
  <xs:element name="IdealAdjustment">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="iaPair" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="iaPair">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="adjustingIdeal" type="xs:string"/>
        <xs:element name="referencePos" type="xs:string"/>
        <xs:element name="adjust" type="xs:decimal"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== dileepcg/KTAB/examples/smp/doc/example.xml
<?xml version="1.0" encoding="UTF-8"?>
<Scenario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="smp.xsd">
  <name>DummyData_3Dim</name>
  <desc>A very simple test of multi-dim SMP, using psuedonyms</desc>
  <prngSeed>100</prngSeed>
  
  <ModelParameters>
    <StateTransitions>Deterministic</StateTransitions>
    <ResolutionVoting>CubicProportional</ResolutionVoting>
    <ResolutionPCE>Markov</ResolutionPCE>
  </ModelParameters>
  
  <Dimensions>
    <dName>FirstDim</dName>
    <dName>SecondDim</dName>
    <dName>YADN</dName>
  </Dimensions>
  
  <Actors>
    <Actor>
      <name>Alice</name>
      <description>One of the SMP actors</description>
      <capability>72.2</capability>
      <Position>
        <dCoord>42.1</dCoord>
        <dCoord>15.7</dCoord>
      </Position>
      <Salience>
        <dSal>83.8</dSal>
        <dSal>97.2</dSal>
      </Salience>
    </Actor>
    
    <Actor>
      <name>Bob</name>
      <description>The second SMP actor</description>
      <capability>72.2</capability>
      <Position>
        <dCoord>42.1</dCoord>
        <dCoord>15.7</dCoord>
      </Position>
      <Salience>
        <dSal>83.8</dSal>
        <dSal>97.2</dSal>
      </Salience>
    </Actor>
    
    <Actor>
      <name>Carol</name>
      <description>Third SMP actor</description>
      <capability>72.2</capability>
      <Position>
        <dCoord>42.1</dCoord>
        <dCoord>15.7</dCoord>
      </Position>
      <Salience>
        <dSal>83.8</dSal>
        <dSal>97.2</dSal>
      </Salience>
    </Actor>
    
  </Actors>
  
  
  <IdealAdjustment>
    <iaPair>
      <adjustingIdeal>Alice</adjustingIdeal>
      <referencePos>Alice</referencePos>
      <adjust>0.87</adjust>
    </iaPair>
    <iaPair>
      <adjustingIdeal>Bob</adjustingIdeal>
      <referencePos>Bob</referencePos>
      <adjust>0.75</adjust>
    </iaPair>
    <iaPair>
      <adjustingIdeal>Bob</adjustingIdeal>
      <referencePos>Alice</referencePos>
      <adjust>0.07</adjust>
    </iaPair>
  </IdealAdjustment>
</Scenario>
