=== dileepcg/KTAB/examples/smp/doc/smpSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="Scenario">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="name" type="xs:string"/>
        <xs:element name="desc" type="xs:string"/>
        <xs:element name="prngSeed" type="xs:string"/>
        <xs:element ref="ModelParameters" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="Dimensions" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="Actors"/>
        <xs:element ref="IdealAdjustment" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="ModelParameters">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="VictoryProbModel" type="VictoryProbModelEnum"/>
        <xs:element name="PCEModel" type="ProbCondorcetElectionModelEnum"/>
        <xs:element name="StateTransitions" type="StateTransitionEnum"/>
        <xs:element name="VotingRule" type="VotingRuleEnum"/>
        <xs:element name="BigRAdjust" type="BigRAdjustEnum"/>
        <xs:element name="BigRRange" type="BigRRangeEnum"/>
        <xs:element name="ThirdPartyCommit" type="ThirdPartyCommitEnum"/>
        <xs:element name="InterVecBrgn" type="InterVecBrgnEnum"/>
        <xs:element name="BargnModel" type="BargnModelEnum"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:simpleType name="VictoryProbModelEnum">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Linear"/>
      <xs:enumeration value="Square"/>
      <xs:enumeration value="Quartic"/>
      <xs:enumeration value="Octic"/>
      <xs:enumeration value="Binary"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="ProbCondorcetElectionModelEnum">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Conditional"/>
      <xs:enumeration value="MarkovIncentive"/>
      <xs:enumeration value="MarkovUniform"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="ThirdPartyCommitEnum">
    <xs:restriction base="xs:string">
      <xs:enumeration value="NoCommit"/>
      <xs:enumeration value="SemiCommit"/>
      <xs:enumeration value="FullCommit"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="StateTransitionEnum">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Deterministic"/>
      <xs:enumeration value="Stochastic"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="VotingRuleEnum">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Binary"/>
      <xs:enumeration value="PropBin"/>
      <xs:enumeration value="Proportional"/>
      <xs:enumeration value="PropCbc"/>
      <xs:enumeration value="Cubic"/>
      <xs:enumeration value="ASymProsp"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="BigRAdjustEnum">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Full"/>
      <xs:enumeration value="TwoThirds"/>
      <xs:enumeration value="Half"/>
      <xs:enumeration value="OneThird"/>
      <xs:enumeration value="No"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="BigRRangeEnum">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Min"/>
      <xs:enumeration value="Mid"/>
      <xs:enumeration value="Max"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="InterVecBrgnEnum">
    <xs:restriction base="xs:string">
      <xs:enumeration value="S1P1"/>
      <xs:enumeration value="S2P2"/>
      <xs:enumeration value="S2PMax"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="BargnModelEnum">
    <xs:restriction base="xs:string">
      <xs:enumeration value="InitOnlyInterp"/>
      <xs:enumeration value="InitRcvrInterp"/>
      <xs:enumeration value="PWCompInterp"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:element name="Dimensions">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="dName" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="dName">
    <xs:simpleType>
      <xs:restriction base="xs:string">
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="Actors">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Actor"  minOccurs="3" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Actor">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="name" type="xs:string"/>
        <xs:element name="description" type="xs:string"/>
        <xs:element name="capability">
          <xs:simpleType>
            <xs:restriction base="xs:decimal">
              <xs:minInclusive value="0.0"/>
              <xs:maxInclusive value="1000.0"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element ref="Position"/>
        <xs:element ref="Salience"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Position">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="dCoord" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="dCoord">
    <xs:simpleType>
      <xs:restriction base="xs:decimal">
        <xs:minInclusive value="0.0"/>
        <xs:maxInclusive value="100.0"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="Salience">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="dSal" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="dSal">
    <xs:simpleType>
      <xs:restriction base="xs:decimal">
        <xs:minInclusive value="0.0"/>
        <xs:maxInclusive value="100.0"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="IdealAdjustment">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="iaPair" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="iaPair">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="adjustingIdeal" type="xs:string"/>
        <xs:element name="referencePos" type="xs:string"/>
        <xs:element name="adjust" type="xs:decimal"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== dileepcg/KTAB/examples/smp/doc/smpExample.xml
<?xml version="1.0" encoding="UTF-8"?>
<Scenario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="smpSchema.xsd">
  <name>DummyData_3Dim</name>
  <desc>A very simple test of multi-dim SMP, using psuedonyms</desc>
  <prngSeed>03507583219545544127</prngSeed>
  
 <ModelParameters>
    <VictoryProbModel>Linear</VictoryProbModel>
    <PCEModel>MarkovIncentive</PCEModel>
    <StateTransitions>Deterministic</StateTransitions> 
    
    <VotingRule>PropCbc</VotingRule>
    <BigRAdjust>OneThird</BigRAdjust>
    <BigRRange>Mid</BigRRange>
    <ThirdPartyCommit>SemiCommit</ThirdPartyCommit>
    <InterVecBrgn>S2P2</InterVecBrgn>
    <BargnModel>InitOnlyInterp</BargnModel>
  </ModelParameters>
  
  <Dimensions>
    <dName>FirstDim</dName>
    <dName>SecondDim</dName>
    <dName>YADN</dName>
  </Dimensions>
  
  <Actors>
    <Actor>
      <name>Alice</name>
      <description>One of the SMP actors</description>
      <capability>72.2</capability>
      <Position>
        <dCoord>42.1</dCoord>
        <dCoord>15.7</dCoord>
      </Position>
      <Salience>
        <dSal>83.8</dSal>
        <dSal>97.2</dSal>
      </Salience>
    </Actor>
    
    <Actor>
      <name>Bob</name>
      <description>The second SMP actor</description>
      <capability>72.2</capability>
      <Position>
        <dCoord>42.1</dCoord>
        <dCoord>15.7</dCoord>
      </Position>
      <Salience>
        <dSal>83.8</dSal>
        <dSal>97.2</dSal>
      </Salience>
    </Actor>
    
    <Actor>
      <name>Carol</name>
      <description>Third SMP actor</description>
      <capability>72.2</capability>
      <Position>
        <dCoord>42.1</dCoord>
        <dCoord>15.7</dCoord>
      </Position>
      <Salience>
        <dSal>83.8</dSal>
        <dSal>97.2</dSal>
      </Salience>
    </Actor>
    
    <Actor>
      <name>David</name>
      <description>Fourth SMP actor</description>
      <capability>63.8</capability>
      <Position>
        <dCoord>55.9</dCoord>
        <dCoord>39.8</dCoord>
      </Position>
      <Salience>
        <dSal>11.2</dSal>
        <dSal>63.8</dSal>
      </Salience>
    </Actor>
    
  </Actors>
  
  
  <IdealAdjustment>
    <iaPair>
      <adjustingIdeal>Alice</adjustingIdeal>
      <referencePos>Alice</referencePos>
      <adjust>0.87</adjust>
    </iaPair>
    
    <iaPair>
      <adjustingIdeal>Bob</adjustingIdeal>
      <referencePos>Bob</referencePos>
      <adjust>0.75</adjust>
    </iaPair>
    
    <iaPair>
      <adjustingIdeal>Bob</adjustingIdeal>
      <referencePos>Alice</referencePos>
      <adjust>0.07</adjust>
    </iaPair>
    
    
    <iaPair>
      <adjustingIdeal>Carol</adjustingIdeal>
      <referencePos>Carol</referencePos>
      <adjust>0.65</adjust>
    </iaPair>
    
    
    <iaPair>
      <adjustingIdeal>Carol</adjustingIdeal>
      <referencePos>David</referencePos>
      <adjust>0.13</adjust>
    </iaPair>
    
    
    <iaPair>
      <adjustingIdeal>David</adjustingIdeal>
      <referencePos>David</referencePos>
      <adjust>0.57</adjust>
    </iaPair>
  </IdealAdjustment>
</Scenario>

=== dileepcg/KTAB/examples/smp/doc/dummyData_3Dim.xml
<?xml version="1.0" encoding="UTF-8"?>
<Scenario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="smpSchema.xsd">
  <name>DummyData_3Dim</name>
  <desc>Dummy scenario to test reading format</desc>
  <prngSeed>03707583219545544125</prngSeed>
  <Dimensions>
    <dName>Pstn1</dName>
    <dName>Pstn2</dName>
    <dName>Pstn3</dName>
  </Dimensions>
  <Actors>
    <Actor>
      <name>SActor-00</name>
      <description>Random Spatial Actor</description>
      <capability>102.543</capability>
      <Position>
        <dCoord>75.79</dCoord>
        <dCoord>6.37</dCoord>
        <dCoord>70.45</dCoord>
      </Position>
      <Salience>
        <dSal>49.53</dSal>
        <dSal>5.91</dSal>
        <dSal>28.15</dSal>
      </Salience>
    </Actor>
    <Actor>
      <name>SActor-01</name>
      <description>Random Spatial Actor</description>
      <capability>53.393</capability>
      <Position>
        <dCoord>82.72</dCoord>
        <dCoord>73.5</dCoord>
        <dCoord>64.0</dCoord>
      </Position>
      <Salience>
        <dSal>30.33</dSal>
        <dSal>21.22</dSal>
        <dSal>24.79</dSal>
      </Salience>
    </Actor>
    <Actor>
      <name>SActor-02</name>
      <description>Random Spatial Actor</description>
      <capability>129.643</capability>
      <Position>
        <dCoord>82.45</dCoord>
        <dCoord>90.89</dCoord>
        <dCoord>0.07</dCoord>
      </Position>
      <Salience>
        <dSal>48.47</dSal>
        <dSal>13.55</dSal>
        <dSal>34.62</dSal>
      </Salience>
    </Actor>
    <Actor>
      <name>SActor-03</name>
      <description>Random Spatial Actor</description>
      <capability>75.92</capability>
      <Position>
        <dCoord>62.52</dCoord>
        <dCoord>50.82</dCoord>
        <dCoord>62.33</dCoord>
      </Position>
      <Salience>
        <dSal>20.76</dSal>
        <dSal>39.24</dSal>
        <dSal>22.21</dSal>
      </Salience>
    </Actor>
    <Actor>
      <name>SActor-04</name>
      <description>Random Spatial Actor</description>
      <capability>63.224</capability>
      <Position>
        <dCoord>82.34</dCoord>
        <dCoord>45.77</dCoord>
        <dCoord>73.31</dCoord>
      </Position>
      <Salience>
        <dSal>40.96</dSal>
        <dSal>25.43</dSal>
        <dSal>22.59</dSal>
      </Salience>
    </Actor>
    <Actor>
      <name>SActor-05</name>
      <description>Random Spatial Actor</description>
      <capability>120.048</capability>
      <Position>
        <dCoord>84.48</dCoord>
        <dCoord>33.7</dCoord>
        <dCoord>88.11</dCoord>
      </Position>
      <Salience>
        <dSal>22.92</dSal>
        <dSal>39.35</dSal>
        <dSal>15.42</dSal>
      </Salience>
    </Actor>
    <Actor>
      <name>SActor-06</name>
      <description>Random Spatial Actor</description>
      <capability>54.178</capability>
      <Position>
        <dCoord>70.96</dCoord>
        <dCoord>33.46</dCoord>
        <dCoord>90.36</dCoord>
      </Position>
      <Salience>
        <dSal>31.75</dSal>
        <dSal>27.93</dSal>
        <dSal>26.03</dSal>
      </Salience>
    </Actor>
  </Actors>
</Scenario>
